# Setup Environment Variables for MHA PWA
# This script helps you create .env.local with Supabase credentials

Write-Host "🔧 MyHealthAlly PWA - Environment Setup" -ForegroundColor Cyan
Write-Host ""

$envFile = ".env.local"

if (Test-Path $envFile) {
    Write-Host "⚠️  .env.local already exists" -ForegroundColor Yellow
    $overwrite = Read-Host "Overwrite? (y/N)"
    if ($overwrite -ne "y") {
        Write-Host "Cancelled." -ForegroundColor Gray
        exit 0
    }
}

Write-Host "📝 Please provide your Supabase credentials:" -ForegroundColor White
Write-Host "   Get them from: Supabase Dashboard → Settings → API" -ForegroundColor Gray
Write-Host ""

$supabaseUrl = Read-Host "Supabase URL (e.g., https://xxxxx.supabase.co)"
$supabaseKey = Read-Host "Supabase Anon Key (starts with eyJ...)"

if ([string]::IsNullOrWhiteSpace($supabaseUrl) -or [string]::IsNullOrWhiteSpace($supabaseKey)) {
    Write-Host "❌ Both values are required!" -ForegroundColor Red
    exit 1
}

$content = @"
# Supabase Configuration
# Generated by setup-env.ps1
NEXT_PUBLIC_SUPABASE_URL=$supabaseUrl
NEXT_PUBLIC_SUPABASE_ANON_KEY=$supabaseKey

# SoloPractice API (if needed)
NEXT_PUBLIC_API_BASE_URL=http://localhost:3000
"@

$content | Out-File -FilePath $envFile -Encoding utf8

Write-Host ""
Write-Host "✅ .env.local created successfully!" -ForegroundColor Green
Write-Host ""
Write-Host "📋 Next steps:" -ForegroundColor Yellow
Write-Host "   1. Run migration in Supabase Dashboard (if not done)" -ForegroundColor White
Write-Host "   2. Start dev server: npm run dev" -ForegroundColor White
Write-Host "   3. Open: http://localhost:3000/provider/dashboard" -ForegroundColor White
Write-Host ""

